version: '3'
services:
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - user-service
      - product-service
      - order-service

  user-service:
    build:
      context: ./user-service
    ports:
      - "8001:8000"

  product-service:
    build:
      context: ./product-service
    ports:
      - "8002:8000"

  order-service:
    build:
      context: ./order-service
    ports:
      - "8003:8000"
